# Generated by Django 2.1.4 on 2018-12-21 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Συγγραφέας',
                'verbose_name_plural': 'Συγγραφείς',
                'db_table': 'author',
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=50, unique=True)),
                ('pages', models.PositiveSmallIntegerField(default=0)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('abstract', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, max_length='255', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('authors', models.ManyToManyField(to='mainapp.Author')),
            ],
            options={
                'verbose_name': 'Βιβλίο',
                'verbose_name_plural': 'Βιβλία',
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Κατηγορία Βιβλίου',
                'verbose_name_plural': 'Κατηγορίες Βιβλίων',
                'db_table': 'category',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Χώρα',
                'verbose_name_plural': 'Χώρες',
                'db_table': 'country',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('classification', models.CharField(blank=True, max_length=255)),
                ('cancel_date', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank='True')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Book')),
            ],
            options={
                'verbose_name': 'Εισαγωγή',
                'verbose_name_plural': 'Εισαγωγές',
                'db_table': 'entry',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Book')),
            ],
            options={
                'verbose_name': 'Κράτηση',
                'verbose_name_plural': 'Κρατήσεις',
                'db_table': 'hold',
                'ordering': ['book'],
            },
        ),
        migrations.CreateModel(
            name='HoldStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Κατάσταση Κρατήσεων',
                'verbose_name_plural': 'Καταστάσεις Κρατήσεων',
                'db_table': 'hold_status',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Γλώσσα',
                'verbose_name_plural': 'Γλώσσες',
                'db_table': 'language',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lend_days', models.PositiveSmallIntegerField(default=20)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Δανεισμός',
                'verbose_name_plural': 'Δανεισμοί',
                'db_table': 'lend',
                'ordering': ['-lend_date'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Country')),
            ],
            options={
                'verbose_name': 'Εκδοτικός Οίκος',
                'verbose_name_plural': 'Εκδοτικοί Οίκοι',
                'db_table': 'publisher',
                'ordering': ['pub_name'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete='models.PROTECT', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Πρόταση',
                'verbose_name_plural': 'Προτάσεις',
                'db_table': 'suggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hold',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mainapp.HoldStatus'),
        ),
        migrations.AddField(
            model_name='hold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='lends',
            field=models.ManyToManyField(through='mainapp.Lend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='mainapp.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(related_name='book_comments', through='mainapp.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='holds',
            field=models.ManyToManyField(related_name='book_holds', through='mainapp.Hold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Publisher'),
        ),
    ]
