# Generated by Django 2.1.4 on 2019-01-21 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Επωνυμία Συγγραφέα')),
                ('bio', models.TextField(blank=True, verbose_name='Βιογραφικό/Πληροφορίες')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Συγγραφέας',
                'verbose_name_plural': 'Συγγραφείς',
                'db_table': 'author',
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος βιβλίου')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('pages', models.PositiveSmallIntegerField(default=0, verbose_name='Αριθμός σελίδων')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Διαστάσεις')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Βάρος (γραμμάρια)')),
                ('published_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Έτος έκδοσης')),
                ('published_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Μήνας έκδοσης')),
                ('revision', models.PositiveSmallIntegerField(default=1, verbose_name='Αριθμός έκδοσης')),
                ('abstract', models.TextField(blank=True, verbose_name='Περίληψη')),
                ('image', models.ImageField(default='default_book.png', upload_to='book_covers', verbose_name='Εξώφυλλο')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Δημιουργία')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Τροποποίηση')),
                ('authors', models.ManyToManyField(related_name='books', to='main.Author', verbose_name='Συγγραφείς')),
            ],
            options={
                'verbose_name': 'Βιβλίο',
                'verbose_name_plural': 'Βιβλία',
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Περιγραφή Κατηγορίας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Κατηγορία Βιβλίου',
                'verbose_name_plural': 'Κατηγορίες Βιβλίων',
                'db_table': 'category',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1 αστέρι'), (2, '2 αστέρια'), (3, '3 αστέρια'), (4, '4 αστέρια'), (5, '5 αστέρια')], default=0, verbose_name='Αξιολόγηση')),
                ('body', models.TextField(blank=True, verbose_name='Σχόλια')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Ημερομηνία καταχώρησης')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Όνομα χρήστη')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Κωδικός Χώρας')),
                ('description', models.CharField(max_length=100, verbose_name='Περιγραφή Χώρας')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Χώρα',
                'verbose_name_plural': 'Χώρες',
                'db_table': 'country',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία εισαγωγής')),
                ('classification', models.CharField(blank=True, max_length=255, verbose_name='Πληροφορίες ταξινόμησης')),
                ('cancel_date', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία ακύρωσης')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
            options={
                'verbose_name': 'Εισαγωγή',
                'verbose_name_plural': 'Εισαγωγές',
                'db_table': 'entry',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία κράτησης')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Book')),
            ],
            options={
                'verbose_name': 'Κράτηση',
                'verbose_name_plural': 'Κρατήσεις',
                'db_table': 'hold',
                'ordering': ['book'],
            },
        ),
        migrations.CreateModel(
            name='HoldStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Κατάσταση Κρατήσεων',
                'verbose_name_plural': 'Καταστάσεις Κρατήσεων',
                'db_table': 'hold_status',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Περιγραφή γλώσσας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Γλώσσα',
                'verbose_name_plural': 'Γλώσσες',
                'db_table': 'language',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία δανεισμού')),
                ('lend_days', models.PositiveSmallIntegerField(default=20, verbose_name='Διάρκεια δανεισμού (μέρες)')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία επιστροφής')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Entry', verbose_name='Αριθμός αντιτύπου')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Όνομα χρήστη')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=255, verbose_name='Επωνυμία')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Πόλη')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Διεύθυνση')),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name='Ταχ. Κώδικας')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Τηλέφωνο')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Country', verbose_name='Χώρα')),
            ],
            options={
                'verbose_name': 'Εκδοτικός Οίκος',
                'verbose_name_plural': 'Εκδοτικοί Οίκοι',
                'db_table': 'publisher',
                'ordering': ['pub_name'],
            },
        ),
        migrations.AddField(
            model_name='hold',
            name='lend',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hold', to='main.Lend'),
        ),
        migrations.AddField(
            model_name='hold',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.HoldStatus'),
        ),
        migrations.AddField(
            model_name='hold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AddField(
            model_name='entry',
            name='lends',
            field=models.ManyToManyField(related_name='lends', through='main.Lend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='main.Category', verbose_name='Κατηγορίες'),
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(related_name='user_comments', through='main.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='holds',
            field=models.ManyToManyField(related_name='user_holds', through='main.Hold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='main.Language', verbose_name='Γλώσσα'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='main.Publisher', verbose_name='Εκδότης'),
        ),
    ]
