# Generated by Django 2.1.4 on 2018-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['author_name'], 'verbose_name': 'Συγγραφέας', 'verbose_name_plural': 'Συγγραφείς'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Βιβλίο', 'verbose_name_plural': 'Βιβλία'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['description'], 'verbose_name': 'Κατηγορία Βιβλίου', 'verbose_name_plural': 'Κατηγορίες Βιβλίων'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['description'], 'verbose_name': 'Χώρα', 'verbose_name_plural': 'Χώρες'},
        ),
        migrations.AlterModelOptions(
            name='hold',
            options={'ordering': ['book'], 'verbose_name': 'Κράτηση', 'verbose_name_plural': 'Κρατήσεις'},
        ),
        migrations.AlterModelOptions(
            name='holdstatus',
            options={'ordering': ['description'], 'verbose_name': 'Κατάσταση Κρατήσεων', 'verbose_name_plural': 'Καταστάσεις Κρατήσεων'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['description'], 'verbose_name': 'Γλώσσα', 'verbose_name_plural': 'Γλώσσες'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['pub_name'], 'verbose_name': 'Εκδοτικός Οίκος', 'verbose_name_plural': 'Εκδοτικοί Οίκοι'},
        ),
        migrations.AlterField(
            model_name='holdstatus',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
