# Generated by Django 2.1.4 on 2018-12-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Πόλη'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Country', verbose_name='Χώρα'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pub_name',
            field=models.CharField(max_length=255, verbose_name='Επωνυμία'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ταχ. Κώδικας'),
        ),
    ]
