# Generated by Django 2.1.4 on 2018-12-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='book_data', serialize=False, to='mainapp.Book')),
                ('active_holds', models.PositiveIntegerField(default=0)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('num_lends', models.PositiveIntegerField(default=0)),
                ('num_comments', models.PositiveIntegerField(default=0)),
                ('sum_stars', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Βιβλίο',
                'verbose_name_plural': 'Βιβλία',
                'db_table': 'book_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='user_data', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lends', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('holds', models.PositiveIntegerField(default=0)),
                ('suggestions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Χρήστης',
                'verbose_name_plural': 'Χρήστες',
                'db_table': 'user_data',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='published',
        ),
        migrations.AddField(
            model_name='book',
            name='published_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
