# Generated by Django 2.1.4 on 2018-12-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181227_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
