# Generated by Django 2.1.4 on 2018-12-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181218_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mainapp.HoldStatus'),
        ),
    ]
