# Generated by Django 2.1.4 on 2018-12-25 07:32

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181223_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Επωνυμία Συγγραφέα')),
                ('bio', models.TextField(blank=True, verbose_name='Βιογραφικό/Πληροφορίες')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Συγγραφέας',
                'verbose_name_plural': 'Συγγραφείς',
                'db_table': 'author_list',
                'ordering': ['author_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Περιγραφή Κατηγορίας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Κατηγορία Βιβλίου',
                'verbose_name_plural': 'Κατηγορίες Βιβλίων',
                'db_table': 'category_list',
                'ordering': ['description'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Περιγραφή γλώσσας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Γλώσσα',
                'verbose_name_plural': 'Γλώσσες',
                'db_table': 'language_list',
                'ordering': ['description'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublisherList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=255, verbose_name='Επωνυμία')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Πόλη')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Διεύθυνση')),
                ('zip', models.CharField(blank=True, max_length=20, verbose_name='Ταχ. Κώδικας')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Τηλέφωνο')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Εκδοτικός Οίκος',
                'verbose_name_plural': 'Εκδοτικοί Οίκοι',
                'db_table': 'publisher_list',
                'ordering': ['pub_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Όνομα Χρήστη')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Όνομα')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Επώνυμο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Κωδικός')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Διαχειριστής')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Εκδότης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Δημιουργήθηκε')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Τελελυταία σύνδεση')),
            ],
            options={
                'verbose_name': 'Χρήστης',
                'verbose_name_plural': 'Χρήστες',
                'db_table': 'user_list',
                'ordering': ['username'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='mainapp.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='mainapp.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='mainapp.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='holds',
            field=models.ManyToManyField(related_name='holds', through='mainapp.Hold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lends',
            field=models.ManyToManyField(related_name='lends', through='mainapp.Lend', to=settings.AUTH_USER_MODEL),
        ),
    ]
