# Generated by Django 2.1.4 on 2018-12-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181227_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBestChoices',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='book_best_choices', serialize=False, to='mainapp.Book')),
            ],
            options={
                'db_table': 'book_best_choices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookTopTitles',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='book_top_titles', serialize=False, to='mainapp.Book')),
            ],
            options={
                'db_table': 'book_top_titles',
                'managed': False,
            },
        ),
    ]
