# Generated by Django 2.1.4 on 2019-01-05 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_bookbestchoices_booktoptitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTopPicks',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='book_best_choices', serialize=False, to='mainapp.Book')),
            ],
            options={
                'db_table': 'book_best_choices',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.ManyToManyField(related_name='user_comments', through='mainapp.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='holds',
            field=models.ManyToManyField(related_name='user_holds', through='mainapp.Hold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='mainapp.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='mainapp.Publisher'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, verbose_name='Σχόλια'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 αστέρι'), (2, '2 αστέρια'), (3, '3 αστέρια'), (4, '4 αστέρια'), (5, '5 αστέρια')], default=0, verbose_name='Αξιολόγηση'),
        ),
    ]
