# Generated by Django 2.1.4 on 2018-12-26 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181225_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=50, unique=True)),
                ('pages', models.PositiveSmallIntegerField(default=0)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('abstract', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, max_length='255', upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active_holds', models.PositiveIntegerField(default=0)),
                ('num_entries', models.PositiveIntegerField(default=0)),
                ('num_lends', models.PositiveIntegerField(default=0)),
                ('num_comments', models.PositiveIntegerField(default=0)),
                ('sum_stars', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Βιβλίο',
                'verbose_name_plural': 'Βιβλία',
                'db_table': 'book_details',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.png', upload_to='book_covers'),
        ),
    ]
