# Generated by Django 2.1.4 on 2019-01-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190105_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='hold',
            name='lend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Lend'),
        ),
    ]
