# Generated by Django 2.1.4 on 2018-12-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181226_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNewest',
            fields=[
                ('book', models.OneToOneField(on_delete='models.CASCADE', primary_key=True, serialize=False, to='mainapp.Book')),
            ],
            options={
                'db_table': 'book_newest',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book.png', upload_to='book_covers'),
        ),
    ]
