# Generated by Django 2.1.4 on 2019-01-08 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_hold_lend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hold',
            name='lend',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hold', to='mainapp.Lend'),
        ),
    ]
