# Generated by Django 2.1.4 on 2019-01-12 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190111_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Ημερομηνία καταχώρησης'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Όνομα χρήστη'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία κράτησης'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Entry', verbose_name='Αριθμός αντιτύπου'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='lend_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία δανεισμού'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='lend_days',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Διάρκεια δανεισμού (μέρες)'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία επιστροφής'),
        ),
        migrations.AlterField(
            model_name='lend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Όνομα χρήστη'),
        ),
    ]
