# Generated by Django 2.1.4 on 2019-01-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190112_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='mainapp.Author', verbose_name='Συγγραφείς'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='mainapp.Category', verbose_name='Κατηγορίες'),
        ),
    ]
