# Generated by Django 2.1.4 on 2019-01-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_lenddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendData',
            fields=[
                ('lend', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='lend_data', serialize=False, to='mainapp.Lend')),
                ('delay', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'lend_data',
                'managed': False,
            },
        ),
    ]
