# Generated by Django 2.1.4 on 2019-01-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_lenddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
