insert into category (description) values ('Αθλητισμός');
insert into category (description) values ('Αυτοβελτίωση');
insert into category (description) values ('Βιογραφίες');
insert into category (description) values ('Εγκυκλοπαίδειες');
insert into category (description) values ('Εκμάθηση γλωσσών');
insert into category (description) values ('Επιχειρήσεις');
insert into category (description) values ('Εφηβικά');
insert into category (description) values ('Θετικές Επιστήμες');
insert into category (description) values ('Θρησκεία - Πνευματικότητα');
insert into category (description) values ('Ιατρική');
insert into category (description) values ('Ιστορία');
insert into category (description) values ('Καλές Τέχνες');
insert into category (description) values ('Κοινωνικές και ανθρωπιστικές επιστήμες');
insert into category (description) values ('Κόμικς');
insert into category (description) values ('Λεξικά');
insert into category (description) values ('Λογοτεχνία');
insert into category (description) values ('Μαγειρική');
insert into category (description) values ('Οικογένεια');
insert into category (description) values ('Οικολγία - Περιβάλλον');
insert into category (description) values ('Παιδαγωγική');
insert into category (description) values ('Παιδικά');
insert into category (description) values ('Περιοδικά');
insert into category (description) values ('Πολιτική - Κοινωνία');
insert into category (description) values ('Σχολικά βιβλία και βοηθήματα');
insert into category (description) values ('Ταξίδια');
insert into category (description) values ('Τεχνολογία');
insert into category (description) values ('Υγεία - Σώμα - Διατροφή');
insert into category (description) values ('Χάρτες & άτλαντες');
insert into category (description) values ('Ψυχαγωγία');
