insert into country(description, code) values('Αγία Λουκία','LC');
insert into country(description, code) values('Άγιος Βαρθολομαίος','BL');
insert into country(description, code) values('Άγιος Βικέντιος και Γρεναδίνες','VC');
insert into country(description, code) values('Άγιος Μαρίνος','SM');
insert into country(description, code) values('Άγιος Μαρτίνος (Γαλλία)','MF');
insert into country(description, code) values('Άγιος Μαρτίνος (Ολλανδία)','SX');
insert into country(description, code) values('Άγιος Χριστόφορος και Νέβις','KN');
insert into country(description, code) values('Αζερμπαϊτζάν','AZ');
insert into country(description, code) values('Αίγυπτος','EG');
insert into country(description, code) values('Αιθιοπία','ET');
insert into country(description, code) values('Αϊτή','HT');
insert into country(description, code) values('Ακτή Ελεφαντοστού','CI');
insert into country(description, code) values('Αλβανία','AL');
insert into country(description, code) values('Αλγερία','DZ');
insert into country(description, code) values('Αμερικανικές Παρθένοι Νήσοι','VI');
insert into country(description, code) values('Αμερικανική Σαμόα','AS');
insert into country(description, code) values('Ανατολικό Τιμόρ','TL');
insert into country(description, code) values('Ανγκόλα','AO');
insert into country(description, code) values('Ανγκουίλα','AI');
insert into country(description, code) values('Ανδόρρα','AD');
insert into country(description, code) values('Ανταρκτική','AQ');
insert into country(description, code) values('Αντίγκουα και Μπαρμπούντα','AG');
insert into country(description, code) values('Απομακρυσμένες Νησίδες των Ηνωμένων Πολιτειών','UM');
insert into country(description, code) values('Αργεντινή','AR');
insert into country(description, code) values('Αρμενία','AM');
insert into country(description, code) values('Αρούμπα','AW');
insert into country(description, code) values('Αυστραλία','AU');
insert into country(description, code) values('Αυστρία','AT');
insert into country(description, code) values('Αφγανιστάν','AF');
insert into country(description, code) values('Βανουάτου','VU');
insert into country(description, code) values('Βατικανό','VA');
insert into country(description, code) values('Βέλγιο','BE');
insert into country(description, code) values('Βενεζουέλα','VE');
insert into country(description, code) values('Βερμούδες','BM');
insert into country(description, code) values('Βιετνάμ','VN');
insert into country(description, code) values('Βολιβία','BO');
insert into country(description, code) values('Βόρεια Κορέα','KP');
insert into country(description, code) values('Βόρειες Μαριάνες Νήσοι','MP');
insert into country(description, code) values('Βοσνία-Ερζεγοβίνη','BA');
insert into country(description, code) values('Βουλγαρία','BG');
insert into country(description, code) values('Βραζιλία','BR');
insert into country(description, code) values('Βρετανικές Παρθένοι Νήσοι','VG');
insert into country(description, code) values('Βρετανικό Έδαφος Ινδικού Ωκεανού','IO');
insert into country(description, code) values('Γαλλία','FR');
insert into country(description, code) values('Γαλλικά Νότια και Ανταρκτικά Εδάφη','TF');
insert into country(description, code) values('Γαλλική Γουιάνα','GF');
insert into country(description, code) values('Γαλλική Πολυνησία','PF');
insert into country(description, code) values('Γερμανία','DE');
insert into country(description, code) values('Γεωργία','GE');
insert into country(description, code) values('Γιβραλτάρ','GI');
insert into country(description, code) values('Γκάμπια','GM');
insert into country(description, code) values('Γκαμπόν','GA');
insert into country(description, code) values('Γκάνα','GH');
insert into country(description, code) values('Γκέρνσεϊ','GG');
insert into country(description, code) values('Γκουάμ','GU');
insert into country(description, code) values('Γουαδελούπη','GP');
insert into country(description, code) values('Γουατεμάλα','GT');
insert into country(description, code) values('Γουιάνα','GY');
insert into country(description, code) values('Γουινέα','GN');
insert into country(description, code) values('Γουινέα-Μπισσάου','GW');
insert into country(description, code) values('Γρενάδα','GD');
insert into country(description, code) values('Γροιλανδία','GL');
insert into country(description, code) values('Δανία','DK');
insert into country(description, code) values('Δομινίκα','DM');
insert into country(description, code) values('Δομινικανή Δημοκρατία','DO');
insert into country(description, code) values('Δυτική Όχθη','PS');
insert into country(description, code) values('Δυτική Σαχάρα','EH');
insert into country(description, code) values('Ελ Σαλβαδόρ','SV');
insert into country(description, code) values('Ελβετία','CH');
insert into country(description, code) values('Ελλάδα','GR');
insert into country(description, code) values('Ερυθραία','ER');
insert into country(description, code) values('Εσθονία','EE');
insert into country(description, code) values('Ζάμπια','ZM');
insert into country(description, code) values('Ζιμπάμπουε','ZW');
insert into country(description, code) values('Ηνωμένα Αραβικά Εμιράτα','AE');
insert into country(description, code) values('Ηνωμένες Πολιτείες Αμερικής','US');
insert into country(description, code) values('Ηνωμένο Βασίλειο','GB');
insert into country(description, code) values('Ιαπωνία','JP');
insert into country(description, code) values('Ινδία','IN');
insert into country(description, code) values('Ινδονησία','ID');
insert into country(description, code) values('Ιορδανία','JO');
insert into country(description, code) values('Ιράκ','IQ');
insert into country(description, code) values('Ιράν','IR');
insert into country(description, code) values('Ιρλανδία','IE');
insert into country(description, code) values('Ισημερινή Γουινέα','GQ');
insert into country(description, code) values('Ισημερινός','EC');
insert into country(description, code) values('Ισλανδία','IS');
insert into country(description, code) values('Ισπανία','ES');
insert into country(description, code) values('Ισραήλ','IL');
insert into country(description, code) values('Ιταλία','IT');
insert into country(description, code) values('Καζακστάν','KZ');
insert into country(description, code) values('Καμερούν','CM');
insert into country(description, code) values('Καμπότζη','KH');
insert into country(description, code) values('Καναδάς','CA');
insert into country(description, code) values('Κατάρ','QA');
insert into country(description, code) values('Κέιμαν Νήσοι','KY');
insert into country(description, code) values('Κεντροαφρικανική Δημοκρατία','CF');
insert into country(description, code) values('Κένυα','KE');
insert into country(description, code) values('Κίνα','CN');
insert into country(description, code) values('Κιργιζία','KG');
insert into country(description, code) values('Κιριμπάτι','KI');
insert into country(description, code) values('Κογκό','CG');
insert into country(description, code) values('Κολομβία','CO');
insert into country(description, code) values('Κομόρες','KM');
insert into country(description, code) values('Κόστα Ρίκα','CR');
insert into country(description, code) values('Κούβα','CU');
insert into country(description, code) values('Κουβέιτ','KW');
insert into country(description, code) values('Κουρασάο','CW');
insert into country(description, code) values('Κροατία','HR');
insert into country(description, code) values('Κύπρος','CY');
insert into country(description, code) values('Λαϊκή Δημοκρατία του Κογκό','CD');
insert into country(description, code) values('Λάος','LA');
insert into country(description, code) values('Λεσότο','LS');
insert into country(description, code) values('Λεττονία','LV');
insert into country(description, code) values('Λευκορωσία','BY');
insert into country(description, code) values('Λίβανος','LB');
insert into country(description, code) values('Λιβερία','LR');
insert into country(description, code) values('Λιβύη','LY');
insert into country(description, code) values('Λιθουανία','LT');
insert into country(description, code) values('Λίχτενσταϊν','LI');
insert into country(description, code) values('Λουξεμβούργο','LU');
insert into country(description, code) values('Μαγιότ','YT');
insert into country(description, code) values('Μαδαγασκάρη','MG');
insert into country(description, code) values('Μακάο','MO');
insert into country(description, code) values('Μαλαισία','MY');
insert into country(description, code) values('Μαλάουι','MW');
insert into country(description, code) values('Μαλδίβες','MV');
insert into country(description, code) values('Μάλι','ML');
insert into country(description, code) values('Μάλτα','MT');
insert into country(description, code) values('Μαρόκο','MA');
insert into country(description, code) values('Μαρτινίκα','MQ');
insert into country(description, code) values('Μαυρίκιος','MU');
insert into country(description, code) values('Μαυριτανία','MR');
insert into country(description, code) values('Μαυροβούνιο','ME');
insert into country(description, code) values('Μεξικό','MX');
insert into country(description, code) values('Μιανμάρ (Βιρμανία)','MM');
insert into country(description, code) values('Μογγολία','MN');
insert into country(description, code) values('Μοζαμβίκη','MZ');
insert into country(description, code) values('Μολδαβία','MD');
insert into country(description, code) values('Μονακό','MC');
insert into country(description, code) values('Μοντσερράτ','MS');
insert into country(description, code) values('Μπανγκλαντές','BD');
insert into country(description, code) values('Μπαρμπάντος','BB');
insert into country(description, code) values('Μπαχάμες','BS');
insert into country(description, code) values('Μπαχρέιν','BH');
insert into country(description, code) values('Μπελίζ','BZ');
insert into country(description, code) values('Μπενίν','BJ');
insert into country(description, code) values('Μποναίρ, Άγιος Ευστάθιος και Σάμπα (Bonaire, Sint Eustatius and Saba)','BQ');
insert into country(description, code) values('Μποτσουάνα','BW');
insert into country(description, code) values('Μπουβέ','BV');
insert into country(description, code) values('Μπουρκίνα Φάσο','BF');
insert into country(description, code) values('Μπουρούντι','BI');
insert into country(description, code) values('Μπουτάν','BT');
insert into country(description, code) values('Μπρουνέι','BN');
insert into country(description, code) values('Ναμίμπια','NA');
insert into country(description, code) values('Ναουρού','NR');
insert into country(description, code) values('Νέα Ζηλανδία','NZ');
insert into country(description, code) values('Νέα Καληδονία','NC');
insert into country(description, code) values('Νεπάλ','NP');
insert into country(description, code) values('Νησί Νόρφολκ','NF');
insert into country(description, code) values('Νησιά Κόκος (Keeling)','CC');
insert into country(description, code) values('Νησιά Πίτκερν','PN');
insert into country(description, code) values('Νήσοι Κουκ','CK');
insert into country(description, code) values('Νήσοι Μάρσαλ','MH');
insert into country(description, code) values('Νήσοι Νότια Γεωργία και Νότιες Σάντουιτς','GS');
insert into country(description, code) values('Νήσοι Σολομώντα','SB');
insert into country(description, code) values('Νήσοι Φερόες','FO');
insert into country(description, code) values('Νήσοι Φώκλαντ','FK');
insert into country(description, code) values('Νήσοι Χερντ και Μακντόναλντ','HM');
insert into country(description, code) values('Νήσος Αγίας Ελένης','SH');
insert into country(description, code) values('Νήσος Μαν','IM');
insert into country(description, code) values('Νήσος των Χριστουγέννων','CX');
insert into country(description, code) values('Νίγηρας','NE');
insert into country(description, code) values('Νιγηρία','NG');
insert into country(description, code) values('Νικαράγουα','NI');
insert into country(description, code) values('Νιούε','NU');
insert into country(description, code) values('Νορβηγία','NO');
insert into country(description, code) values('Νότια Αφρική','ZA');
insert into country(description, code) values('Νότια Κορέα','KR');
insert into country(description, code) values('Νότιο Σουδάν','SS');
insert into country(description, code) values('Ολλανδία (Κάτω Χώρες)','NL');
insert into country(description, code) values('Ολλανδικές Αντίλλες','AN');
insert into country(description, code) values('Ομάν','OM');
insert into country(description, code) values('Ομόσπονδες Πολιτείες της Μικρονησίας','FM');
insert into country(description, code) values('Ονδούρα','HN');
insert into country(description, code) values('Ουαλίς και Φουτουνά','WF');
insert into country(description, code) values('Ουγγαρία','HU');
insert into country(description, code) values('Ουγκάντα','UG');
insert into country(description, code) values('Ουζμπεκιστάν','UZ');
insert into country(description, code) values('Ουκρανία','UA');
insert into country(description, code) values('Ουρουγουάη','UY');
insert into country(description, code) values('Πακιστάν','PK');
insert into country(description, code) values('Παλάου','PW');
insert into country(description, code) values('Παναμάς','PA');
insert into country(description, code) values('Παπούα Νέα Γουινέα','PG');
insert into country(description, code) values('Παραγουάη','PY');
insert into country(description, code) values('ΠΓΔΜ','MK');
insert into country(description, code) values('Περού','PE');
insert into country(description, code) values('Πολωνία','PL');
insert into country(description, code) values('Πορτογαλία','PT');
insert into country(description, code) values('Πουέρτο Ρίκο','PR');
insert into country(description, code) values('Πράσινο Ακρωτήρι','CV');
insert into country(description, code) values('Ρεϊνιόν','RE');
insert into country(description, code) values('Ρουάντα','RW');
insert into country(description, code) values('Ρουμανία','RO');
insert into country(description, code) values('Ρωσία','RU');
insert into country(description, code) values('Σαιν Πιερ και Μικελόν','PM');
insert into country(description, code) values('Σαμόα','WS');
insert into country(description, code) values('Σάο Τομέ και Πρίνσιπε','ST');
insert into country(description, code) values('Σαουδική Αραβία','SA');
insert into country(description, code) values('Σβάλμπαρντ','SJ');
insert into country(description, code) values('Σενεγάλη','SN');
insert into country(description, code) values('Σερβία','RS');
insert into country(description, code) values('Σεϋχέλλες','SC');
insert into country(description, code) values('Σιγκαπούρη','SG');
insert into country(description, code) values('Σιέρα Λεόνε','SL');
insert into country(description, code) values('Σλοβακία','SK');
insert into country(description, code) values('Σλοβενία','SI');
insert into country(description, code) values('Σομαλία','SO');
insert into country(description, code) values('Σουαζιλάνδη','SZ');
insert into country(description, code) values('Σουδάν','SD');
insert into country(description, code) values('Σουηδία','SE');
insert into country(description, code) values('Σουρινάμ','SR');
insert into country(description, code) values('Σρι Λάνκα','LK');
insert into country(description, code) values('Συρία','SY');
insert into country(description, code) values('Ταϊβάν','TW');
insert into country(description, code) values('Ταϊλάνδη','TH');
insert into country(description, code) values('Τανζανία','TZ');
insert into country(description, code) values('Τατζικιστάν','TJ');
insert into country(description, code) values('Τερκς και Κέικος','TC');
insert into country(description, code) values('Τζαμάικα','JM');
insert into country(description, code) values('Τζέρσεϊ','JE');
insert into country(description, code) values('Τζιμπουτί','DJ');
insert into country(description, code) values('Τόγκα','TO');
insert into country(description, code) values('Τόγκο','TG');
insert into country(description, code) values('Τοκελάου','TK');
insert into country(description, code) values('Τουβαλού','TV');
insert into country(description, code) values('Τουρκία','TR');
insert into country(description, code) values('Τουρκμενιστάν','TM');
insert into country(description, code) values('Τρινιντάντ και Τομπάγκο','TT');
insert into country(description, code) values('Τσαντ','TD');
insert into country(description, code) values('Τσεχία','CZ');
insert into country(description, code) values('Τυνησία','TN');
insert into country(description, code) values('Υεμένη','YE');
insert into country(description, code) values('Φιλιππίνες','PH');
insert into country(description, code) values('Φινλανδία','FI');
insert into country(description, code) values('Φίτζι','FJ');
insert into country(description, code) values('Χιλή','CL');
insert into country(description, code) values('Χονγκ Κονγκ','HK');
insert into country(description, code) values('Ώλαντ','AX');
